export type PaymentMethod = "upi" | "cod";
export type PaymentStatus = "paid" | "pending_cod" | "failed";
export type OrderStatus = "confirmed" | "dispatched" | "delivered" | "cancelled";

export interface Address {
  line1: string;
  area: string;
  city: string;
  pincode: string;
}

export interface OrderItem {
  product_id: string;
  name: string;
  qty: number;
  price: number;
}

export interface Order {
  id?: string; // UUID, generated by DB
  created_at?: string; // generated by DB
  customer_name: string;
  customer_mobile: string;
  address: Address;
  items: OrderItem[];
  slot_id: string;
  slot_date: string; // ISO string or YYYY-MM-DD
  payment_method: PaymentMethod;
  payment_status: PaymentStatus;
  razorpay_order_id: string | null;
  wa_opt_in: boolean;
  order_notes: string;
  status: OrderStatus;
}

export interface Slot {
  id: string; // e.g. "SLOT-AM"
  label: string; // e.g. "11:00 AM – 1:00 PM"
  cutoff_time: string; // "09:30:00"
  max_capacity: number;
  confirmed_orders: number;
  is_active: boolean;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string;
  ingredients: string[];
  shelf_life: string;
  storage_instructions: string;
  price_label: string; // "₹349 · 6 pieces · approx 300g"
  price: number;
  badge?: string;
  image_url: string;
}
