export type PaymentMethod = "upi" | "cod" | "razorpay";
export type PaymentStatus = "paid" | "pending_cod" | "failed" | "pending";
export type OrderStatus = 
  | "needs_verification" 
  | "pending" 
  | "confirmed" 
  | "dispatched" 
  | "delivered" 
  | "cancelled"
  | "payment_pending"
  | "cod_pending"
  | "payment_failed";

export interface Address {
  line1: string;
  area: string;
  city: string;
  pincode: string;
}

export interface OrderItem {
  product: Product;
  quantity: number;
  selectedSlotId: string;
  selectedDate: string;
}

export interface Order {
  id?: string; // UUID, generated by DB
  display_id?: string; // e.g. ORD-123456
  created_at?: string; // generated by DB
  customer_name: string;
  customer_mobile: string;
  address_line1: string;
  address_area: string;
  address_city: string;
  address_pincode: string;
  items: OrderItem[];
  slot_id: string;
  slot_date: string; // ISO string or YYYY-MM-DD
  payment_method: PaymentMethod;
  payment_status: PaymentStatus;
  razorpay_order_id: string | null;
  payment_link_id?: string | null;
  payment_id?: string | null;
  wa_opt_in: boolean;
  order_notes: string;
  status: OrderStatus;
  total_amount: number;
  coupon_id?: string | null;
  discount_amount?: number;
  original_total?: number;
  final_total?: number;
  delivery_option?: 'delivery' | 'pickup';
  delivery_slots?: { label: string };
}

export interface Coupon {
  id: string;
  code: string;
  type: 'percentage' | 'flat';
  value: number;
  min_order_amount: number;
  max_uses: number | null;
  uses_count: number;
  valid_from: string;
  valid_until: string | null;
  is_first_time_only: boolean;
  is_active: boolean;
  created_at: string;
}

export interface CouponUse {
  id: string;
  coupon_id: string;
  order_id: string;
  user_phone: string;
  discount_applied: number;
  used_at: string;
}

export interface Slot {
  id: string; // e.g. "SLOT-AM"
  label: string; // e.g. "11:00 AM – 1:00 PM"
  cutoff_time: string; // "09:30:00"
  max_capacity: number;
  confirmed_orders?: number;
  is_active: boolean;
  slot_date?: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string;
  ingredients: string[];
  shelf_life: string;
  storage_instructions: string;
  price_label?: string; // Optional now, since we have pieces
  price: number;
  pieces: number;
  badge?: string;
  image_url: string;
  is_active?: boolean;
}
